Add tomato vs cucumber classifier model
mrjslau/TOP2018 pull request #3
Opened 2018-09-19 20:29 UTC by EdvardasDlugauskas

It can tell whether the image is a tomato or a cucumber

2018-09-19 20:48 UTC, EdvardasDlugauskas commented
Could somebody try to run the project and tell me if it works?

If you run into problems on a mac, follow the README.md file in the project root.

2018-09-21 17:04 UTC, marjasi requested changes
Great work and humorous beer addition! However, the project doesn't run on my machine because it can't find the paths to the resource files.

2018-09-21 17:04 UTC, marjasi commented on ShopLens/ImageRecognition/Program.cs
> +            "resources\\model\\model.pb";
For some reason the program 'can't find a part of the path' to all the required files on my machine. It should work and everything seems fine. Weird.

2018-09-21 17:04 UTC, marjasi commented on ShopLens/ImageRecognition/resources/model/labels.txt
> +beer
Nice addition.

2018-09-21 17:04 UTC, marjasi commented on ShopLens/ImageRecognition/Program.cs
> +            "resources\\model\\model.pb";
I even tried changing it to "..\\resources\\model\\model.pb" and it still couldn't find the path.

2018-09-21 17:04 UTC, MellowJay commented on ShopLens/ImageRecognition/TfImageUtil.cs
> +// Taken and adapted from: https://github.com/migueldeicaza/TensorFlowSharp/blob/master/Examples/ExampleCommon/ImageUtil.cs
Maybe we should add this library and credit the author on our master branch README.md?

2018-09-21 17:05 UTC, MellowJay commented on ShopLens/ImageRecognition/Program.cs
> +            "resources\\model\\model.pb";
I mean "..\\resources\\model\\model.pb" to be exact.

2018-09-21 17:27 UTC, marjasi approved these changes

2018-09-21 17:28 UTC, merged